### ISSUE TITLE
Autoflow reflows to one character over the editor's preferred line length

### ISSUE THREAD

**Issue by terrycloth** [atom/autoflow#34] opened 2015-09-01 06:44 UTC
When my editor's preferred line length is 80, Autoflow wraps lines up to *81* characters long. If I actually want the lines to be no more than 80 characters, I have to set the preferred line length to *79*.

**Comment by kebno** [comment] 2015-09-23 17:25
I see this too. Although sometimes it does wrap to 80.

**Comment by ForNeVeR** [comment] 2015-11-14 11:05
Could you please give a reproducible example?

**Comment by kebno** [comment] 2015-11-14 18:20
Sorry, I can't. I don't remember what I was using it with that did or didn't work at the time, and I stopped using it at that time and haven't used it since.
(if it comes up again, I'll immediately try to get a reproducible case)

**Comment by terrycloth** [comment] 2015-11-14 21:32
I couldn't remember an exact instance that this happened, so I tried just testing it on some random text with the "Lorem ipsum" snippet.

In line 10 of the following sample, Autoflow wraps it at character 81. I thought for a second that maybe it was because the 81st character was a period, but changing it to a letter doesn't affect how Autoflow wraps the text.

```
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit
amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur
adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi
ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim
id est laborum.
```

**Comment by terrycloth** [comment] 2015-11-14 22:15
...That's with my Preferred Line Length setting set back to the default 80.

**Comment by ForNeVeR** [comment] 2015-11-15 04:07
I think that is misunderstanding. The line 10 of this text is wrapped exactly _after_ 80 characters. If you want to wrap it on character 79 (a reasonable desire when you're trying to follow something like [PEP 0008](https://www.python.org/dev/peps/pep-0008/), for example), then you should set margin at column 79 in the Atom settings.

**Comment by lee-dohm** [comment] 2015-11-15 05:26
I just tried the text given above. With the Preferred Line Length set to 80, it wraps at the point you specify, but line 10 consists of exactly 80 characters:

```text
in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
         1         2         3         4         5         6         7         8
12345678901234567890123456789012345678901234567890123456789012345678901234567890
```

**Comment by ForNeVeR** [comment] 2015-11-15 09:30
I am testing it on Atom 1.2.0 for Windows and have no issues. I think this bug can be closed.

**Comment by lee-dohm** [comment] 2015-11-16 17:22
Thanks @ForNeVeR. I'd like to hear that this is fixed also for @terrycloth.

**Comment by terrycloth** [comment] 2015-11-16 21:41
Oh, I see. I tried highlighting line 10 in the text sample, and it is indeed 80 characters long. I don't normally look select a line to see its character count, though, I usually just look at the status bar to see what character I'm at. The problem is actually that Atom displays the count for the character to the *right* of the cursor, while I would be inclined to count up to the characters to the *left* of the cursor. For example, when you move the cursor to the very beginning of a line, I would think it ought to say 0 because a blank line has no (visible) characters in it, but the Atom status bar shows 1.

I don't know if this should be refiled as a bug for, um, whatever package handles the line and character count status... But it does seem a little confusing to me.

**Comment by lee-dohm** [comment] 2015-11-16 22:10
Displaying line 1 character 1 for the first character position in a file is pretty standard across editors. I'm pretty sure this has been raised and addressed in the status-bar package. You can find the conversation there. 

Since this is resolved, I'll close the issue when I get back to my desk. Thanks!

**Closed** 2015-11-17 01:52 UTC
Labels: needs-reproduction
