### ISSUE TITLE
Problem with German keyboards under Windows

### ISSUE THREAD

**Issue by derwaldgeist** [atom/autoflow#48] opened 2016-05-14 12:38 UTC
On German keyboards under Windows, the default shortcut is the same that is used for the @ sign (AltGr-Q). This causes unwanted formatting and prevents usage of the @ sign, which is quite annoying.

**Comment by 50Wliu** [comment] 2016-05-14 14:43
This is a duplicate of atom/atom-keymap#35 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-05-14 14:43 UTC

**Comment by derwaldgeist** [comment] 2016-05-14 15:17
OK, thanks for the info.
